name: Gerar APK Automático

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Dar permissão de execução ao Gradle
      run: chmod +x gradlew

    - name: Compilar APK Debug
      run: ./gradlew assembleDebug

    - name: Salvar APK gerado (com retenção mínima de 1 dia)
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
